g12a: Resolve all missing symbols from libui
Fixes errors detected with ELF checks:
error: Unresolved symbol: _ZN7android19GraphicBufferMapper4lockEPK13native_handlejRKNS_4RectEPPvPiS9_
error: Unresolved symbol: _ZN7android19GraphicBufferMapper6unlockEPK13native_handle

Change-Id: I4b5e44c884cc708c98c903eb2621b8b8607f76c9